import {
  MessageStatuses,
  MessageTypes,
  type ChatProps,
  type Message,
} from "./types";

export const testMessages: Message[] = [
  {
    messageId: 1,
    text: "Hello!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.RECEIVED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 10,
  },
  {
    messageId: 2,
    text: "Hi there!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 3,
    text: "How are you?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 4,
    text: "I'm good, thanks!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 5,
    text: "What about you?",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 6,
    text: "I'm doing well too!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 7,
    text: "That's great to hear!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 8,
    text: "What have you been up to?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 9,
    text: "Just working on some projects.",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 10,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 11,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 12,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 13,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 14,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
  {
    messageId: 15,
    text: "Check out this picture!",
    sender: "me",
    images: [
      {
        imageId: 1,
        imageUrl: "https://picsum.photos/seed/picsum/200/300",
        imageAlt: "idk",
        isLocked: true,
      },
      {
        imageId: 2,
        imageUrl: "https://picsum.photos/seed/picsum/200/300",
        imageAlt: "idk",
        isLocked: false,
      },
    ],
    chatId: 1,
    status: MessageStatuses.READ,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.IMAGE,
    cost: 0,
  },
  {
    messageId: 16,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
    cost: 0,
  },
];

export const testChat: ChatProps[] = [
  {
    avatarImage: "https://example.com/avatar1.png",
    avatarFallback: "U1",
    chatLastMessage: {
      text: "Hello!",
      sender: "Mario inviato",
      status: MessageStatuses.SENT,
      deliveredAt: new Date().toISOString(),
      messageId: 0,
      chatId: 0,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
      cost: 0,
    },
    chatId: 1,
  },
  {
    avatarImage: "https://example.com/avatar2.png",
    avatarFallback: "U2",
    chatLastMessage: {
      text: "Hi there!",
      sender: "Luigi",
      status: MessageStatuses.RECEIVED,
      deliveredAt: new Date().toISOString(),
      messageId: 1,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
      cost: 0,
    },
    chatId: 2,
  },
  {
    avatarImage: "https://example.com/avatar3.png",
    avatarFallback: "U3",
    chatLastMessage: {
      text: "How are you?",
      sender: "Peach",
      status: MessageStatuses.DELIVERED,
      deliveredAt: new Date().toISOString(),
      messageId: 2,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
      cost: 0,
    },
    chatId: 3,
  },
  {
    avatarImage: "https://example.com/avatar4.png",
    avatarFallback: "U4",
    chatLastMessage: {
      text: "I'm good, thanks!",
      sender: "Toad",
      status: MessageStatuses.READ,
      deliveredAt: new Date().toISOString(),
      messageId: 3,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
      cost: 0,
    },
    chatId: 4,
  },
  {
    avatarImage: "https://example.com/avatar5.png",
    avatarFallback: "U5",
    chatLastMessage: {
      text: "What about you?",
      sender: "Yoshi",
      status: MessageStatuses.DELIVERED,
      deliveredAt: new Date().toISOString(),
      messageId: 4,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
      cost: 0,
    },
  },
];
