import { MessageStatuses, MessageTypes, type Message } from "./types";

export const testMessages: Message[] = [
  {
    id: 1,
    text: "Hello!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.RECEIVED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 2,
    text: "Hi there!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 3,
    text: "How are you?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 4,
    text: "I'm good, thanks!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 5,
    text: "What about you?",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 6,
    text: "I'm doing well too!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 7,
    text: "That's great to hear!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 8,
    text: "What have you been up to?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 9,
    text: "Just working on some projects.",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 10,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 11,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 12,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 13,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 14,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
  {
    id: 15,
    text: "Check out this picture!",
    sender: "me",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    chatId: 1,
    status: MessageStatuses.READ,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.IMAGE,
  },
  {
    id: 16,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date(),
    readAt: new Date(),
    type: MessageTypes.TEXT,
  },
];
