import {
  MessageStatuses,
  MessageTypes,
  type ChatProps,
  type Message,
} from "./types";

export const testMessages: Message[] = [
  {
    id: 1,
    text: "Hello!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.RECEIVED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 2,
    text: "Hi there!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 3,
    text: "How are you?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 4,
    text: "I'm good, thanks!",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 5,
    text: "What about you?",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 6,
    text: "I'm doing well too!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 7,
    text: "That's great to hear!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 8,
    text: "What have you been up to?",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 9,
    text: "Just working on some projects.",
    sender: "me",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 10,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 11,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 12,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 13,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 14,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
  {
    id: 15,
    text: "Check out this picture!",
    sender: "me",
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
    chatId: 1,
    status: MessageStatuses.READ,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.IMAGE,
  },
  {
    id: 16,
    text: "Sounds interesting!",
    sender: "other",
    chatId: 1,
    status: MessageStatuses.DELIVERED,
    deliveredAt: new Date().toISOString(),
    readAt: new Date().toISOString(),
    type: MessageTypes.TEXT,
  },
];

export const testChat: ChatProps[] = [
  {
    avatarImage: "https://example.com/avatar1.png",
    avatarFallback: "U1",
    chatLastMessage: {
      text: "Hello!",
      sender: "Mario inviato",
      status: MessageStatuses.SENT,
      deliveredAt: new Date().toISOString(),
      id: 0,
      chatId: 0,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
    },
    chatId: 1,
  },
  {
    avatarImage: "https://example.com/avatar2.png",
    avatarFallback: "U2",
    chatLastMessage: {
      text: "Hi there!",
      sender: "Luigi",
      status: MessageStatuses.RECEIVED,
      deliveredAt: new Date().toISOString(),
      id: 1,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
    },
    chatId: 2,
  },
  {
    avatarImage: "https://example.com/avatar3.png",
    avatarFallback: "U3",
    chatLastMessage: {
      text: "How are you?",
      sender: "Peach",
      status: MessageStatuses.DELIVERED,
      deliveredAt: new Date().toISOString(),
      id: 2,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
    },
    chatId: 3,
  },
  {
    avatarImage: "https://example.com/avatar4.png",
    avatarFallback: "U4",
    chatLastMessage: {
      text: "I'm good, thanks!",
      sender: "Toad",
      status: MessageStatuses.READ,
      deliveredAt: new Date().toISOString(),
      id: 3,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
    },
    chatId: 4,
  },
  {
    avatarImage: "https://example.com/avatar5.png",
    avatarFallback: "U5",
    chatLastMessage: {
      text: "What about you?",
      sender: "Yoshi",
      status: MessageStatuses.DELIVERED,
      deliveredAt: new Date().toISOString(),
      id: 4,
      chatId: 1,
      readAt: new Date().toISOString(),
      type: MessageTypes.TEXT,
    },
  },
];
